import React, { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext.jsx'
import { useRestaurant } from '../context/RestaurantContext.jsx'
import { listPaidInvoices } from '../services/invoiceRegisterService.js'

export default function InvoiceRegisterPage() {
  const { formatMoney } = useRestaurant(); const auth = useAuth(); const restaurantId = auth.userContext?.membership?.restaurant_id
  const [filters, setFilters] = useState({ from: '', to: '', status: 'all' }); const [rows, setRows] = useState([]); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState(null)
  async function load() { setLoading(true); try { setRows(await listPaidInvoices(restaurantId, filters)) } catch (e) { window.alert(e.message) } finally { setLoading(false) } }
  useEffect(() => { if (restaurantId) load() }, [restaurantId])
  return <section className="view active"><div className="hero"><div><h2>Facturas cobradas</h2><p>Consulta las facturas válidas y anuladas, con sus productos y valores.</p></div></div>
    <div className="card"><div className="filters"><label>Desde<input type="date" value={filters.from} onChange={e => setFilters({...filters, from:e.target.value})}/></label><label>Hasta<input type="date" value={filters.to} onChange={e => setFilters({...filters, to:e.target.value})}/></label><label>Estado<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="all">Todas</option><option value="valid">No anuladas</option><option value="voided">Anuladas</option></select></label><button className="btn primary" onClick={load}>Aplicar filtros</button></div></div>
    <div className="card section-gap"><div className="section-title"><h3>Registro de facturas</h3><span className="badge">{rows.length} resultados</span></div>{loading?<div className="empty-inline">Cargando…</div>:rows.length?<div className="table-wrap"><table><thead><tr><th>Factura</th><th>Fecha</th><th>Productos</th><th>Subtotal</th><th>IVA</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.invoiceNumber}</b><small>Orden #{row.orderNumber}</small></td><td>{new Date(row.issuedAt).toLocaleString('es-CO')}</td><td>{(row.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0)}</td><td>{formatMoney(row.subtotal)}</td><td>{formatMoney(row.taxTotal)}</td><td><b>{formatMoney(row.total)}</b></td><td><span className={`badge ${row.voided?'danger-badge':'ok-badge'}`}>{row.voided?'Anulada':'Válida'}</span></td><td><button className="mini" onClick={()=>setSelected(row)}>Ver detalle</button></td></tr>)}</tbody></table></div>:<div className="empty-inline">No hay facturas para esos filtros.</div>}</div>
    {selected&&<div className="modal open"><div className="modal-card"><div className="section-title"><h3>{selected.invoiceNumber}</h3><button className="btn" onClick={()=>setSelected(null)}>×</button></div><p className="muted">{new Date(selected.issuedAt).toLocaleString('es-CO')} · {selected.voided?'Anulada':'Válida'}</p><div className="list">{(selected.items||[]).map((item,i)=><div className="row" key={i}><span>{item.quantity} × {item.name}<small>IVA {item.taxRate||0}% · {formatMoney(item.unitPrice)} c/u</small></span><b>{formatMoney(item.amount)}</b></div>)}</div><div className="totals"><div>Subtotal <b>{formatMoney(selected.subtotal)}</b></div><div>IVA <b>{formatMoney(selected.taxTotal)}</b></div><div>Total <b>{formatMoney(selected.total)}</b></div></div></div></div>}</section>
}
