export const ROLE_PRESETS = [
  {
    code: 'owner',
    name: 'Owner / Super Admin',
    icon: '👑',
    description: 'Control total de la empresa, Control Central, sucursales y operación.',
    permissions: '*',
    companyScope: true,
  },
  {
    code: 'corporate_admin',
    name: 'Corporate Administrator / Administrador Corporativo',
    icon: '🏢',
    description: 'Administra la empresa completa: sucursales, personal, catálogo, configuración, reportes e inventario central.',
    permissions: [
      'company.control.view',
      'branches.view', 'branches.manage',
      'staff.view', 'staff.manage',
      'settings.view', 'settings.manage',
      'reports.view',
      'products.view', 'products.catalog.manage', 'products.branch.assign',
      'products.availability.request', 'products.availability.approve',
      'inventory.view', 'inventory.manage', 'inventory.central.manage',
      'inventory.transfer.request', 'inventory.transfer.approve',
      'inventory.transfer.dispatch', 'inventory.transfer.receive',
    ],
    companyScope: true,
  },
  {
    code: 'manager',
    name: 'Manager / Supervisor',
    icon: '🧭',
    description: 'Supervisión operativa de una o varias sucursales, sin acceso a la administración corporativa.',
    permissions: [
      'dashboard.view', 'tables.view', 'tables.manage', 'orders.view', 'orders.create', 'orders.update', 'orders.cancel',
      'kitchen.view', 'kitchen.update', 'bar.view', 'bar.update', 'payments.view', 'payments.create', 'payments.refund',
      'products.view', 'products.availability.request', 'customers.view', 'customers.manage',
      'reservations.view', 'reservations.manage', 'inventory.view',
      'inventory.transfer.request', 'inventory.transfer.receive',
      'reports.view', 'display.view', 'display.manage', 'settings.view',
    ],
    companyScope: false,
  },
  {
    code: 'waiter',
    name: 'Waiter / Mesero',
    icon: '🧾',
    description: 'Mesas, pedidos, comandas y servicio al cliente.',
    permissions: ['dashboard.view', 'tables.view', 'orders.view', 'orders.create', 'orders.update', 'products.view'],
    companyScope: false,
  },
  {
    code: 'cashier',
    name: 'Cashier / Caja',
    icon: '💳',
    description: 'Cobros, pagos parciales, cierre de cuentas y consulta de pedidos.',
    permissions: ['dashboard.view', 'tables.view', 'orders.view', 'payments.view', 'payments.create', 'products.view', 'customers.view'],
    companyScope: false,
  },
  {
    code: 'kitchen',
    name: 'Kitchen / Cocina',
    icon: '🍳',
    description: 'KDS de cocina y estados de preparación.',
    permissions: ['orders.view', 'products.view', 'kitchen.view', 'kitchen.update'],
    companyScope: false,
  },
  {
    code: 'bar',
    name: 'Bar',
    icon: '🍸',
    description: 'Comandas asignadas a barra y estados de preparación.',
    permissions: ['orders.view', 'products.view', 'bar.view', 'bar.update'],
    companyScope: false,
  },
  {
    code: 'inventory',
    name: 'Inventory / Store',
    icon: '📦',
    description: 'Inventario local, movimientos, recetas, recepción y solicitudes de abastecimiento.',
    permissions: [
      'products.view', 'inventory.view', 'inventory.manage',
      'inventory.transfer.request', 'inventory.transfer.receive',
    ],
    companyScope: false,
  },
]
